add_executable(testkit src/testkit.cpp)
# Basic memory bug catcher
target_compile_options(testkit PRIVATE -fsanitize=address -fno-omit-frame-pointer)
target_link_options(testkit PRIVATE -fsanitize=address)
target_link_libraries(testkit PRIVATE tancrypt)
target_include_directories(testkit PRIVATE "${CMAKE_SOURCE_DIR}/include")
add_test(NAME "Pkic Init" COMMAND testkit --pkicInit)
add_test(NAME "Keypair generation" COMMAND testkit --pairGen)
add_test(NAME "Keypair re-generation" COMMAND testkit --pairRegen)
add_test(NAME "Keypair multi-generation" COMMAND testkit --pairMultigen)
add_test(NAME "DER get privkey" COMMAND testkit --getPrivDER)
add_test(NAME "DER get pubkey" COMMAND testkit --getPubDER)
add_test(NAME "DER load privkey" COMMAND testkit --loadPrivDER)
add_test(NAME "DER load pubkey" COMMAND testkit --loadPubDER)
add_test(NAME "PEM priv get" COMMAND testkit --getPrivPEM "${CMAKE_SOURCE_DIR}/data/test_data/priv.pem")
add_test(NAME "PEM pub get" COMMAND testkit --getPubPEM "${CMAKE_SOURCE_DIR}/data/test_data/pub.pem")
add_test(NAME "PEM bundle get" COMMAND testkit --getBundlePEM "${CMAKE_SOURCE_DIR}/data/test_data/bundle.pem")
add_test(NAME "PEM priv string load" COMMAND testkit --loadPrivPEM)
add_test(NAME "PEM pub string load" COMMAND testkit --loadPubPEM)
add_test(NAME "PEM bundle string load" COMMAND testkit --loadBundlePEM)
add_test(NAME "PEM import privkey" COMMAND testkit --importPrivPEM "${CMAKE_SOURCE_DIR}/data/test_data/priv.pem")
add_test(NAME "PEM import pubkey" COMMAND testkit --importPubPEM "${CMAKE_SOURCE_DIR}/data/test_data/pub.pem")
add_test(NAME "PEM import bundle" COMMAND testkit --importBundlePEM "${CMAKE_SOURCE_DIR}/data/test_data/bundle.pem")
add_test(NAME "PEM priv export" COMMAND testkit --exportPrivPEM)
add_test(NAME "PEM pub export" COMMAND testkit --exportPubPEM)
add_test(NAME "PEM bundle export" COMMAND testkit --exportBundlePEM)
add_test(NAME "Encrypt" COMMAND testkit --encrypt)
add_test(NAME "Decrypt" COMMAND testkit --decrypt)
add_test(NAME "Hash" COMMAND testkit --hash)
add_test(NAME "Sign" COMMAND testkit --sign)
add_test(NAME "Verify" COMMAND testkit --verify)
add_test(NAME "AES key constructor v1" COMMAND testkit --aesKeyInit1)
add_test(NAME "AES key constructor v2" COMMAND testkit --aesKeyInit2)
add_test(NAME "AES encrypt v1" COMMAND testkit --aesEncryptV1)
add_test(NAME "AES encrypt v2" COMMAND testkit --aesEncryptV2)
add_test(NAME "AES decrypt v1" COMMAND testkit --aesDecryptV1)
add_test(NAME "AES decrypt v2" COMMAND testkit --aesDecryptV2)
add_test(NAME "AES get nonce" COMMAND testkit --getNonce)
if(DO_TEST)
  add_custom_command(TARGET testkit POST_BUILD COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure)
  endif()

